const StravaData = {
    "models": [
        {
            "id": 16149025517,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Wed, 10/15/2025",
            "start_date_local_raw": 1760554310,
            "start_time": "2025-10-15T13:21:50+0000",
            "start_day": "Wed",
            "distance": "2.11",
            "distance_raw": 2113.57,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "10:33",
            "moving_time_raw": 633,
            "elapsed_time": "10:56",
            "elapsed_time_raw": 656,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/PLLURWTU2DEO4RCOGKLOMFZHCAITF5OBJ7OUMYHZFI2FZECV3CWSRXFRCNX7LTNULZWKK7H4AEL4GO5ZOCZHPYVKGMVG4OUA5B5Q====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "27",
            "elevation_unit": "m",
            "elevation_gain_raw": 26.9206,
            "description": null,
            "activity_url": "https://www.strava.com/activities/16149025517",
            "activity_url_for_twitter": "https://www.strava.com/activities/16149025517?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 2.1 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Samsung Health"
        },
        {
            "id": 16105704324,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Sat, 10/11/2025",
            "start_date_local_raw": 1760207384,
            "start_time": "2025-10-11T12:59:44+0000",
            "start_day": "Sat",
            "distance": "2.06",
            "distance_raw": 2063.63,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "10:22",
            "moving_time_raw": 622,
            "elapsed_time": "10:22",
            "elapsed_time_raw": 622,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/UUECA4GLZJF7JTT6YL4GBMSKM57DQHOFIODOLRORAUQEE3SI47SVLZATAOGT2MLSOD7UZEUWDMUAEKV6ZJ7GDJ65Y7M5I53LGHQQ====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "25",
            "elevation_unit": "m",
            "elevation_gain_raw": 25.2991,
            "description": null,
            "activity_url": "https://www.strava.com/activities/16105704324",
            "activity_url_for_twitter": "https://www.strava.com/activities/16105704324?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 2.0 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Samsung Health"
        },
        {
            "id": 16095626693,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Fri, 10/10/2025",
            "start_date_local_raw": 1760122876,
            "start_time": "2025-10-10T13:31:16+0000",
            "start_day": "Fri",
            "distance": "0.38",
            "distance_raw": 386.043,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "1:46",
            "moving_time_raw": 106,
            "elapsed_time": "1:46",
            "elapsed_time_raw": 106,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/FY5E67Y47ZCMW4JE6CJSBPNSFOZ35X72BTHO3FLNXVJE2IM4UUOII4JLZ37TOZU7LI24TZTVMBHWHIMPIYCCUGA5QUZ34DZPMRVA====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "5",
            "elevation_unit": "m",
            "elevation_gain_raw": 4.68667,
            "description": null,
            "activity_url": "https://www.strava.com/activities/16095626693",
            "activity_url_for_twitter": "https://www.strava.com/activities/16095626693?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.3 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Samsung Health"
        },
        {
            "id": 16095621726,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Fri, 10/10/2025",
            "start_date_local_raw": 1760122303,
            "start_time": "2025-10-10T13:21:43+0000",
            "start_day": "Fri",
            "distance": "0.44",
            "distance_raw": 439.708,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "1:42",
            "moving_time_raw": 102,
            "elapsed_time": "1:52",
            "elapsed_time_raw": 112,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/F2HI7SPPYRSZ4BILUXQ7O2OZWXTTIR4HTDJZJRE6RNZSGAEALSSTMQTFSIR34PSB6SN23IZXPVMVRW3OB44H5J6YXPXBMJESX3NQ====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "0",
            "elevation_unit": "m",
            "elevation_gain_raw": 0.0,
            "description": null,
            "activity_url": "https://www.strava.com/activities/16095621726",
            "activity_url_for_twitter": "https://www.strava.com/activities/16095621726?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.4 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Samsung Health"
        },
        {
            "id": 16095617284,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Fri, 10/10/2025",
            "start_date_local_raw": 1760122031,
            "start_time": "2025-10-10T13:17:11+0000",
            "start_day": "Fri",
            "distance": "0.35",
            "distance_raw": 349.47,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "1:26",
            "moving_time_raw": 86,
            "elapsed_time": "2:12",
            "elapsed_time_raw": 132,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/2UOLKYPLD3KTHOZFJV5DCU6AIQDEH6R2V3ZZDD3YGS53F5W4W7ZRWTHZWI5F3WTR2WJ2BEQIQ7G7VMY2DB5EIOO7SADKTB3H74RA====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "4",
            "elevation_unit": "m",
            "elevation_gain_raw": 4.28407,
            "description": null,
            "activity_url": "https://www.strava.com/activities/16095617284",
            "activity_url_for_twitter": "https://www.strava.com/activities/16095617284?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.3 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Samsung Health"
        },
        {
            "id": 16085365805,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Thu, 10/9/2025",
            "start_date_local_raw": 1760035786,
            "start_time": "2025-10-09T13:19:46+0000",
            "start_day": "Thu",
            "distance": "0.45",
            "distance_raw": 457.143,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "1:35",
            "moving_time_raw": 95,
            "elapsed_time": "1:50",
            "elapsed_time_raw": 110,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/4UL5WFMPVU23BEDNHTSBMHNIHKJUO3ELBY4YT63LLDQGRNRFESV2VWVD4ZI4VKAHXWMSVD3VFUUVO73V7MGMCUR72S4GOZX45TGQ====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "5",
            "elevation_unit": "m",
            "elevation_gain_raw": 4.51091,
            "description": null,
            "activity_url": "https://www.strava.com/activities/16085365805",
            "activity_url_for_twitter": "https://www.strava.com/activities/16085365805?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.4 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Samsung Health"
        },
        {
            "id": 16074558020,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Wed, 10/8/2025",
            "start_date_local_raw": 1759949413,
            "start_time": "2025-10-08T13:20:13+0000",
            "start_day": "Wed",
            "distance": "0.39",
            "distance_raw": 398.867,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "1:17",
            "moving_time_raw": 77,
            "elapsed_time": "3:09",
            "elapsed_time_raw": 189,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/XXZ4GAHDOXMUVOYMAWFO2MMAQR4UP5DFT6C5VVGI4SJDF4HDLAXXAA2VH5K3I7VUUVPM5LXKZHNW2SXMVJADMHIGH65LNE2AVBKA====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "5",
            "elevation_unit": "m",
            "elevation_gain_raw": 4.84364,
            "description": null,
            "activity_url": "https://www.strava.com/activities/16074558020",
            "activity_url_for_twitter": "https://www.strava.com/activities/16074558020?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.3 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Samsung Health"
        },
        {
            "id": 16074471441,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Wed, 10/8/2025",
            "start_date_local_raw": 1759948956,
            "start_time": "2025-10-08T13:12:36+0000",
            "start_day": "Wed",
            "distance": "0.43",
            "distance_raw": 435.269,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "2:00",
            "moving_time_raw": 120,
            "elapsed_time": "2:07",
            "elapsed_time_raw": 127,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/5P5PRHRXM3XDZYP5I733TEZHLZ2ICNYJ3PJENKK65YFAIBEKZE67HAYH7IA7DSWFFCRMDG4TQGSFSEPOEOHMGF2LLP3VYEXWVDXQ====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "5",
            "elevation_unit": "m",
            "elevation_gain_raw": 4.71333,
            "description": null,
            "activity_url": "https://www.strava.com/activities/16074471441",
            "activity_url_for_twitter": "https://www.strava.com/activities/16074471441?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.4 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Samsung Health"
        },
        {
            "id": 15797428002,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Sat, 9/13/2025",
            "start_date_local_raw": 1757791069,
            "start_time": "2025-09-13T13:47:49+0000",
            "start_day": "Sat",
            "distance": "1.03",
            "distance_raw": 1038.3,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "5:16",
            "moving_time_raw": 316,
            "elapsed_time": "5:19",
            "elapsed_time_raw": 319,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/7VNEKYXEY4RRRY4ALBQ4YDFWBMU3CD3EQJ6LR37CYJSG4HHUYL5Y3ATXSOMA2PMAWF7WKGXE2YJXDMKTYCUKPQIVINEW5F5GFCRQ====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "15",
            "elevation_unit": "m",
            "elevation_gain_raw": 14.5013,
            "description": "",
            "activity_url": "https://www.strava.com/activities/15797428002",
            "activity_url_for_twitter": "https://www.strava.com/activities/15797428002?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 1.0 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Strava Android App"
        },
        {
            "id": 15797297245,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Sat, 9/13/2025",
            "start_date_local_raw": 1757790227,
            "start_time": "2025-09-13T13:33:47+0000",
            "start_day": "Sat",
            "distance": "1.07",
            "distance_raw": 1075.4,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "5:43",
            "moving_time_raw": 343,
            "elapsed_time": "5:49",
            "elapsed_time_raw": 349,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/A6KNS546JZ4XHARSVWZPHJBC2YRFKRSULSEZ7YSGX3CJLEOOJCYDOJ4WLWU5YHWOI7ATY3G2G2UVVTGQ2PTEAVSMC6L3X6JAP5BA====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "12",
            "elevation_unit": "m",
            "elevation_gain_raw": 12.2268,
            "description": "",
            "activity_url": "https://www.strava.com/activities/15797297245",
            "activity_url_for_twitter": "https://www.strava.com/activities/15797297245?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 1.0 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Strava Android App"
        },
        {
            "id": 15786375515,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Fri, 9/12/2025",
            "start_date_local_raw": 1757705308,
            "start_time": "2025-09-12T13:58:28+0000",
            "start_day": "Fri",
            "distance": "0.41",
            "distance_raw": 415.6,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "1:39",
            "moving_time_raw": 99,
            "elapsed_time": "1:39",
            "elapsed_time_raw": 99,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/CYBQUZMJUBWUQ47OVWWLPOEXJNKSLFGW6NVAMSNZ7GY3OJR7Q463QJTRHCIN6TUJUWLQCHHOOHAHS74XE6OB5MAN6DIBOV4LY2CQ====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "4",
            "elevation_unit": "m",
            "elevation_gain_raw": 4.30606,
            "description": "",
            "activity_url": "https://www.strava.com/activities/15786375515",
            "activity_url_for_twitter": "https://www.strava.com/activities/15786375515?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.4 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Strava Android App"
        },
        {
            "id": 15786269783,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Fri, 9/12/2025",
            "start_date_local_raw": 1757704648,
            "start_time": "2025-09-12T13:47:28+0000",
            "start_day": "Fri",
            "distance": "0.40",
            "distance_raw": 401.9,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "1:26",
            "moving_time_raw": 86,
            "elapsed_time": "1:30",
            "elapsed_time_raw": 90,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/IPPGCGAFUVWF3NVHCS5OLUZGLWS7KT7MDVKW7NGIJF54B6I5JZFJAGHFRNLGG75IB463X23EQ34IQB6CBDCTPRZCXPF7NM5V7E7A====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "5",
            "elevation_unit": "m",
            "elevation_gain_raw": 4.73106,
            "description": "",
            "activity_url": "https://www.strava.com/activities/15786269783",
            "activity_url_for_twitter": "https://www.strava.com/activities/15786269783?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.4 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Strava Android App"
        },
        {
            "id": 15786223176,
            "name": "Evening Run",
            "sport_type": "Run",
            "display_type": "Run",
            "activity_type_display_name": "Run",
            "private": false,
            "bike_id": null,
            "athlete_gear_id": null,
            "start_date": "Fri, 9/12/2025",
            "start_date_local_raw": 1757704299,
            "start_time": "2025-09-12T13:41:39+0000",
            "start_day": "Fri",
            "distance": "0.44",
            "distance_raw": 441.4,
            "long_unit": "kilometers",
            "short_unit": "km",
            "moving_time": "2:08",
            "moving_time_raw": 128,
            "elapsed_time": "2:11",
            "elapsed_time_raw": 131,
            "trainer": false,
            "static_map": "https://d3o5xota0a1fcr.cloudfront.net/v6/maps/TZ2KAV5DPYMEEFESOXHDEMIFXKV7ETJA4JGMNTFUHGWX3FHOISJLSABVZLKR6CH4WSQXL3WAKON2ZZAWEXH4Z5LZ5FXXACZWS3TQ====",
            "has_latlng": true,
            "commute": null,
            "elevation_gain": "5",
            "elevation_unit": "m",
            "elevation_gain_raw": 4.81333,
            "description": "",
            "activity_url": "https://www.strava.com/activities/15786223176",
            "activity_url_for_twitter": "https://www.strava.com/activities/15786223176?utm_content=126959228\u0026utm_medium=referral\u0026utm_source=twitter",
            "twitter_msg": "went for a 0.4 kilometer Run.",
            "is_changing_type": false,
            "suffer_score": null,
            "tags": {
                "6": false,
                "8": false,
                "9": false,
                "7": false,
                "4": false,
                "11": false,
                "15": false,
                "10": false,
                "5": true
            },
            "selected_tag_type": null,
            "flagged": false,
            "hide_power": false,
            "hide_heartrate": false,
            "visibility": "everyone",
            "device": "Strava Android App"
        }
    ],
    "page": 1,
    "perPage": 20,
    "total": 13
}

export default StravaData;